server {
  bind_address = "0.0.0.0"
  bind_port = "8081"
  trust_domain = "agentguard-it.internal"
  data_dir = "/run/spire/data"
  log_level = "INFO"
  default_x509_svid_ttl = "2m"
  default_jwt_svid_ttl = "2m"
}
plugins {
  DataStore "sql" { plugin_data { database_type = "sqlite3"  connection_string = "/run/spire/data/datastore.sqlite3" } }
  NodeAttestor "join_token" { plugin_data {} }
  KeyManager "memory" { plugin_data {} }
}
